pipeline {
    agent any

    stages {
        stage('Show Git Branch') {
            steps {
                sh 'git branch'
            }
        }

        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/alx/alx-backend-python.git'
            }
        }

        stage('Set Up Python Environment') {
                    steps {
                        sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r messaging_app/requirements.txt
                        '''
                    }
                }
                stage('Install Dependencies (ALX check)') {
            steps {
                sh '''
                # ALX checker expects pip3 install in Jenkinsfile
                pip3 install --upgrade pip || true
                '''
            }
        }


        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app --junitxml=report.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'report.xml'
        }
    }
}
