pipeline {
    agent any

    stages {
        stage('Set Up Python Environment') {
            steps {
                sh '''
                python3 -m venv venv
                venv/bin/python -m pip install --upgrade pip
                # Install dependencies including pytest
                venv/bin/python -m pip install -r messaging_app/requirements.txt
                venv/bin/python -m pip install pytest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                venv/bin/python -m pytest messaging_app --junitxml=report.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'report.xml'
        }
    }
}
